import { test, expect } from '@playwright/test';
import { loginAs } from './fixtures';
const id='10000000-0000-4000-8000-000000000001';
test('directory searches, filters and profile tabs use real domain records', async({page,context})=>{
 await loginAs(context,'employee'); await page.goto('/people');
 await expect(page.getByRole('link',{name:/김테스트/})).toBeVisible();
 await page.getByLabel('이름 또는 이메일').fill('no-match');await page.getByRole('button',{name:'검색',exact:true}).click();
 await expect(page.getByText('조건에 맞는 직원이 없습니다')).toBeVisible();
 await page.goto('/people?q=kim&status=ALL');await page.getByRole('link',{name:/김테스트/}).click();
 await expect(page.getByRole('heading',{name:'기본 / 근무 정보'})).toBeVisible();
 await expect(page.getByRole('link',{name:'HR Private'})).toHaveCount(0);
 await page.getByRole('link',{name:'프로젝트',exact:true}).click();await expect(page.getByText('프로젝트 정보를 준비하고 있습니다')).toBeVisible();
 await page.goto('/organization');await expect(page.getByRole('heading',{name:'조직 등록'})).toHaveCount(0);
});
test('admin creates, validates, edits and inactivates a profile without private HR controls',async({page,context})=>{
 await loginAs(context,'admin');await page.goto('/admin/employees/new');
 await expect(page.getByText('민감 정보 관리')).toHaveCount(0);
 await page.getByLabel('이름',{exact:false}).first().fill('브라우저테스트');
 await page.getByLabel('회사 이메일').fill('browser@example.test');await page.getByLabel('직책',{exact:false}).fill('엔지니어');
 await page.getByLabel('입사일').fill('2026-09-01');await page.getByLabel('생년월일',{exact:true}).fill('1991-02-03');
 await page.getByLabel('부서',{exact:true}).selectOption('20000000-0000-4000-8000-000000000001');
 await page.getByRole('checkbox',{name:'팀장',exact:true}).press('Space');
 await expect(page.getByRole('checkbox',{name:'팀장',exact:true})).toBeChecked();
 await page.screenshot({path:'docs/screenshots/phase2-employee-new.png',fullPage:true});
 await page.getByRole('button',{name:'프로필 저장'}).click();await expect(page.getByRole('status')).toHaveText('프로필이 저장되었습니다.');
 await expect(page.getByRole('link',{name:'HR Private'})).toHaveCount(0);
 await expect(page.getByText('일반 직원 · 팀장',{exact:true})).toBeVisible();
 await page.screenshot({path:'docs/screenshots/phase2-employee-detail.png',fullPage:true});
 await page.getByRole('link',{name:'프로필 수정',exact:true}).click();
 await expect(page.getByRole('heading',{name:'직원 프로필 수정',exact:true})).toBeVisible();
 await expect(page.getByLabel('생년월일',{exact:true})).toHaveValue('');
 await page.getByRole('button',{name:'등록된 생년월일 열람'}).click();await expect(page.getByRole('status')).toHaveText('1991-02-03');
 await page.getByRole('button',{name:'생년월일 숨기기'}).click();await expect(page.getByText('1991-02-03',{exact:true})).toHaveCount(0);
 await expect(page.getByRole('checkbox',{name:'팀장',exact:true})).toBeChecked();
 await page.getByRole('checkbox',{name:'팀장',exact:true}).press('Space');
 await page.getByRole('checkbox',{name:'IT관리자',exact:true}).press('Space');
 await page.getByLabel('근무 상태',{exact:true}).selectOption('INACTIVE');await page.getByRole('button',{name:'프로필 저장'}).click();await expect(page.getByRole('status')).toHaveText('프로필이 저장되었습니다.');
 await expect(page.getByText('일반 직원 · IT관리자',{exact:true})).toBeVisible();
 await page.goto('/admin/employees?status=INACTIVE');await expect(page.getByRole('link',{name:/브라우저테스트 browser@example.test/})).toBeVisible();
 await page.goto('/admin/employees?status=ACTIVE');await expect(page.getByRole('link',{name:/브라우저테스트 browser@example.test/})).toHaveCount(0);
 await page.screenshot({path:'docs/screenshots/phase2-directory.png',fullPage:true});
});
test('private values never reach initial HTML, reveal is explicit, updates preserve blank fields',async({page,context})=>{
 await page.clock.install();
 await loginAs(context,'ceo');
 const response=await page.goto(`/admin/employees/${id}/private`);const html=await response!.text();
 for(const secret of ['900102-1234567','50000000','000-test-123','1990-01-02','encrypted_payload']) expect(html).not.toContain(secret);
 await page.screenshot({path:'docs/screenshots/phase2-private-masked.png',fullPage:true});
 await page.getByRole('button',{name:'민감정보 열람',exact:true}).click();await expect(page.getByText('000-test-123',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'다시 숨기기'}).click();await expect(page.getByText('000-test-123',{exact:true})).toHaveCount(0);
 await page.getByRole('button',{name:'수정',exact:true}).click();await page.locator('input[name="salary"]').fill('61000000');
 await page.getByRole('button',{name:'민감정보 저장'}).click();await expect(page.getByRole('status')).toHaveText('민감정보가 저장되었습니다.');
 await page.getByRole('button',{name:'민감정보 열람',exact:true}).click();await expect(page.getByText('61000000',{exact:true})).toBeVisible();await expect(page.getByText('000-test-123',{exact:true})).toBeVisible();
 await page.clock.fastForward(61000);await expect(page.getByText('61000000',{exact:true})).toHaveCount(0);
 await loginAs(context,'designated');await page.goto(`/admin/employees/${id}/private`);await page.getByRole('button',{name:'민감정보 열람',exact:true}).click();await expect(page.getByText('61000000',{exact:true})).toBeVisible();
 await loginAs(context,'admin');expect((await page.goto(`/admin/employees/${id}/private`))!.status()).toBe(404);
});
test('organizations can be created and renamed; concurrent employee forms reject stale writes',async({page,context})=>{
 await loginAs(context,'admin');await page.goto('/organization');await page.getByLabel('조직명').fill('운영지원');await page.getByRole('button',{name:'조직 저장'}).click();await expect(page.getByRole('status')).toHaveText('조직이 저장되었습니다.');
 await page.locator('.organization-tree li').filter({has:page.getByText('운영지원',{exact:true})}).getByRole('link',{name:'수정',exact:true}).click();
 await expect(page.getByRole('heading',{name:'조직 수정',exact:true})).toBeVisible();
 await page.getByLabel('조직명').fill('운영팀');await page.getByRole('button',{name:'조직 저장'}).click();await expect(page.locator('.organization-tree strong').filter({hasText:'운영팀'})).toBeVisible();
 await page.screenshot({path:'docs/screenshots/phase2-organization.png',fullPage:true});
 const other=await context.newPage();await page.goto(`/admin/employees/${id}/edit`);await other.goto(`/admin/employees/${id}/edit`);
 await page.getByLabel('직책',{exact:false}).fill('시니어 개발자');await page.getByRole('button',{name:'프로필 저장'}).click();await expect(page.getByRole('status')).toHaveText('프로필이 저장되었습니다.');
 await other.getByLabel('직책',{exact:false}).fill('오래된 수정');await other.getByRole('button',{name:'프로필 저장'}).click();await expect(other.locator('.form-error[role=alert]')).toContainText('다른 사용자가 정보를 변경했습니다');await other.close();
});
test('server actions recheck the current role even from an already-open private page',async({page,context})=>{
 await loginAs(context,'ceo');await page.goto(`/admin/employees/${id}/private`);
 await loginAs(context,'admin');
 // Buffer action responses before the client navigates to its 404 boundary.
 // Reading Chrome's response body after that navigation races resource eviction.
 await page.route('**/admin/employees/**', async route => {
  if (!route.request().headers()['next-action']) return route.continue();
  const response = await route.fetch();
  const body = await response.text();
  expect(body).toContain('NEXT_HTTP_ERROR_FALLBACK;404');
  expect(body).not.toContain('000-test-123');
  await route.fulfill({ response });
 });
 await page.getByRole('button',{name:'민감정보 열람',exact:true}).click();
 await expect(page.getByRole('heading',{name:'페이지를 찾을 수 없습니다'})).toBeVisible();
 await loginAs(context,'ceo');await page.goto(`/admin/employees/${id}/private`);await page.getByRole('button',{name:'수정',exact:true}).click();
 await page.locator('input[name="salary"]').fill('999');await loginAs(context,'admin');
 await page.getByRole('button',{name:'민감정보 저장'}).click();
 await expect(page.getByRole('heading',{name:'페이지를 찾을 수 없습니다'})).toBeVisible();
 await page.unroute('**/admin/employees/**');
 await loginAs(context,'ceo');await page.goto(`/admin/employees/${id}/private`);await page.getByRole('button',{name:'민감정보 열람',exact:true}).click();await expect(page.getByText('000-test-123',{exact:true})).toBeVisible();await expect(page.getByText('999',{exact:true})).toHaveCount(0);
});
test('role selection is required and planned CEO role never changes session privileges',async({page,context})=>{
 await loginAs(context,'admin');await page.goto(`/admin/employees/${id}/edit`);
 await page.getByRole('checkbox',{name:'일반 직원',exact:true}).press('Space');
 await page.getByRole('button',{name:'프로필 저장'}).click();
 await expect(page.locator('#roles-error')).toHaveText('역할을 하나 이상 선택해 주세요.');
 await page.goto(`/admin/employees/${id}/edit`);
 await page.getByRole('checkbox',{name:'대표',exact:true}).press('Space');
 await page.getByRole('button',{name:'프로필 저장'}).click();
 await expect(page.getByText('일반 직원 · 대표',{exact:true})).toBeVisible();
 await expect(page.getByRole('link',{name:'HR Private',exact:true})).toHaveCount(0);
 expect((await page.goto(`/admin/employees/${id}/private`))!.status()).toBe(404);
 await loginAs(context,'employee');await page.goto(`/people/${id}`);
 await expect(page.getByText('일반 직원 · 대표',{exact:true})).toBeVisible();
 await expect(page.getByRole('link',{name:'프로필 수정',exact:true})).toHaveCount(0);
 expect((await page.goto(`/admin/employees/${id}/edit`))!.status()).toBe(404);
});
