import { test,expect } from '@playwright/test';
import { loginAs,tokenFor } from './fixtures';
const onboarding='a0000000-0000-4000-8000-000000000001',offboarding='a0000000-0000-4000-8000-000000000002',documentId='a1000000-0000-4000-8000-000000000001',family='a3000000-0000-4000-8000-000000000001';
const secret='CEO-ONLY resignation reason fixture';
test('six Figma operation screens and mobile layout keep private data masked',async({page,context})=>{
 await loginAs(context,'admin');for(const [path,shot] of [['/admin/onboarding','onboarding'],['/admin/offboarding','offboarding'],['/announcements','announcements'],['/admin/settings/birthday-email','birthday']]){const response=await page.goto(path);expect(response!.status()).toBe(200);expect(await response!.text()).not.toContain(secret);await page.screenshot({path:`docs/screenshots/phase7-${shot}.png`,fullPage:true});}
 await loginAs(context,'employee');for(const [path,shot] of [['/family-events','family-board'],['/family-events/new','family-registration']]){await page.goto(path);await page.screenshot({path:`docs/screenshots/phase7-${shot}.png`,fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.goto('/family-events/new');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);await page.screenshot({path:'docs/screenshots/phase7-family-mobile.png',fullPage:true});
});
test('onboarding multiple owners, manual tasks and retained completion history',async({page,context})=>{
 await loginAs(context,'admin');await page.goto('/admin/onboarding/'+onboarding);const row=page.getByRole('row').filter({has:page.getByText('Gmail',{exact:true})});await expect(row).toContainText('김테스트');await expect(row).toContainText('이동료');await row.getByRole('link',{name:'수정',exact:true}).click();await page.getByLabel('메모',{exact:true}).fill('Browser onboarding note');await page.getByLabel('진행 상태').selectOption('IN_PROGRESS');await page.getByRole('button',{name:'항목 저장'}).click();await expect(page.getByRole('status')).toHaveText('저장했습니다.');await expect(row).toContainText('Browser onboarding note');
 await page.getByRole('button',{name:'온보딩 완료',exact:true}).click();await expect(page.locator('.form-error[role=alert]')).toBeVisible();
 for(let i=0;i<8;i++){await page.getByRole('row').nth(i+1).getByRole('link',{name:'수정',exact:true}).click();await page.getByLabel('진행 상태').selectOption('NOT_APPLICABLE');await page.getByRole('button',{name:'항목 저장'}).click();await expect(page).not.toHaveURL(/task=/);}
 await page.getByRole('button',{name:'온보딩 완료',exact:true}).click();await expect(page.getByText('처리가 완료되었습니다. 직원 정보와 처리 이력은 보존됩니다.')).toBeVisible();await page.locator('.operation-history summary').click();await expect(page.locator('.operation-history')).toContainText('처리 완료');
});
test('CEO audited reveal and private file upload/download; Admin finishes despite assigned assets',async({page,context})=>{
 await loginAs(context,'ceo');await page.goto('/admin/offboarding/'+offboarding);expect(await page.content()).not.toContain(secret);await page.getByRole('button',{name:'퇴사 사유 열람'}).click();await expect(page.getByLabel('퇴사 사유',{exact:true})).toHaveValue(secret);await page.getByRole('button',{name:'숨기기',exact:true}).click();expect(await page.content()).not.toContain(secret);
 await page.getByLabel('사직서 첨부').setInputFiles({name:'browser-letter.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nprivate browser letter\n%%EOF')});await page.getByRole('button',{name:'사직서 업로드'}).click();await expect(page.getByRole('link',{name:'browser-letter.pdf 다운로드'})).toBeVisible();const download=await context.request.get(await page.getByRole('link',{name:'browser-letter.pdf 다운로드'}).getAttribute('href')||'');expect(download.status()).toBe(200);expect(await download.text()).toContain('private browser letter');expect(download.headers()['cache-control']).toContain('no-store');
 await loginAs(context,'admin');const response=await page.goto('/admin/offboarding/'+offboarding);expect(await response!.text()).not.toContain('browser-letter.pdf');await expect(page.getByText('미반납 장비 1대')).toBeVisible();await page.getByRole('row').nth(1).getByRole('link',{name:'수정',exact:true}).click();await page.getByLabel('진행 상태').selectOption('DONE');await page.getByRole('button',{name:'항목 저장'}).click();await expect(page).not.toHaveURL(/task=/);await page.getByLabel('미사용 연차 확인',{exact:true}).check();await page.getByRole('button',{name:'퇴사 처리 완료 · INACTIVE 전환'}).click();await expect(page.getByText('처리가 완료되었습니다. 직원 정보와 처리 이력은 보존됩니다.')).toBeVisible();await expect(page.getByText('미반납 장비 1대')).toBeVisible();await expect(page.locator('.operation-person')).toContainText('INACTIVE');
});
test('announcements draft and explicit publication; registration and board content remain separate',async({page,context})=>{
 await loginAs(context,'admin');await page.goto('/announcements/new');await page.getByLabel('제목',{exact:true}).fill('Browser announcement');await page.getByLabel('내용',{exact:true}).fill('<script>visible text only</script>');await page.getByRole('button',{name:'공지 저장'}).click();await expect(page.getByRole('status')).toHaveText('저장했습니다.');const announcement=new URL(page.url()).pathname;
 await loginAs(context,'employee');expect((await page.goto(announcement))!.status()).toBe(404);await loginAs(context,'admin');await page.goto(announcement+'/edit');await page.getByLabel('회사 게시판에 게시').check();await page.getByRole('button',{name:'공지 저장'}).click();await expect(page.getByRole('status')).toHaveText('저장했습니다.');await loginAs(context,'employee');await page.goto(announcement);await expect(page.getByText('<script>visible text only</script>',{exact:true})).toBeVisible();expect((await page.goto(announcement+'/edit'))!.status()).toBe(404);
 await page.goto('/family-events/new');await page.getByLabel('행사일').fill('2026-10-10');await page.getByLabel('제목',{exact:true}).fill('PRIVATE browser event');await page.getByLabel('대표자에게 전달할 내용 (비공개)').fill('PRIVATE browser venue and contact');await page.getByRole('button',{name:'경조사 등록',exact:true}).click();await expect(page.getByRole('status')).toHaveText('저장했습니다.');const own=new URL(page.url()).pathname;await expect(page.getByText(/대표자 알림: 발송 대기/)).toBeVisible();await expect(page.getByLabel('게시판 제목')).toHaveValue('');await expect(page.getByLabel('게시판 내용')).toHaveValue('');await page.getByLabel('게시판 제목').fill('Public browser event');await page.getByLabel('게시판 내용').fill('Public congratulations');await page.getByRole('button',{name:'게시판에 공유',exact:true}).click();await expect(page.locator('form').filter({has:page.getByLabel('게시판 제목')}).locator('input[name=version]')).toHaveValue('1');
 await loginAs(context,'expense');const board=await page.goto('/family-events');expect(await board!.text()).not.toContain('PRIVATE browser');await expect(page.getByText('Public congratulations',{exact:true})).toBeVisible();expect((await page.goto(own))!.status()).toBe(404);
 await loginAs(context,'employee');await page.goto(own);await page.getByRole('button',{name:'게시 내리기'}).click();await expect(page.getByLabel('게시판 제목')).toHaveValue('');await page.goto('/family-events');await expect(page.getByText('Public congratulations',{exact:true})).toHaveCount(0);
});
test('birthday yearly template preview, saved content and secured cron fail safely without Gmail credentials',async({page,context})=>{
 await loginAs(context,'admin');await page.goto('/admin/settings/birthday-email?year=2027');await page.getByLabel('메일 제목').fill('{{name}}님, 생일 축하합니다');await page.getByLabel('메일 본문').fill('{{birthday}} 오늘 즐거운 하루 보내세요.');await expect(page.locator('.mail-preview')).toContainText('김서연님, 생일 축하합니다');await expect(page.locator('.mail-preview')).toContainText('10-05 오늘');await page.getByRole('button',{name:'템플릿 저장'}).click();await expect(page.locator('#birthday-template input[name=version]')).toHaveValue('1');await page.reload();await expect(page.getByLabel('메일 제목')).toHaveValue('{{name}}님, 생일 축하합니다');
 expect((await context.request.get('/api/cron/company-mail')).status()).toBe(401);expect((await context.request.get('/api/cron/company-mail?secret=test-cron-secret-at-least-32-characters-long')).status()).toBe(401);const result=await context.request.get('/api/cron/company-mail',{headers:{Authorization:'Bearer test-cron-secret-at-least-32-characters-long'}});expect(result.status()).toBe(503);expect(await result.text()).not.toContain('PRIVATE');
});
test('private operations deny forged URLs, RSC, documents, RPCs and replayed server actions',async({page,context})=>{
 for(const role of ['employee','leader','expense','it','division','admin','designated']){
 await loginAs(context,role);expect((await context.request.get('/api/offboarding/documents/'+documentId)).status()).toBe(404);
 const rsc=await context.request.get('/admin/offboarding/'+offboarding,{headers:{RSC:'1'}});for(const value of [secret,'CEO-ONLY-letter.pdf','private browser letter','test-operations-service'])expect(await rsc.text()).not.toContain(value);
 if(!['admin','designated'].includes(role)){for(const path of ['/admin/onboarding/'+onboarding,'/admin/offboarding/'+offboarding,'/admin/settings/birthday-email'])expect((await page.goto(path))!.status()).toBe(404);}
 const headers={Authorization:'Bearer '+tokenFor(role)};const reason=await context.request.post('http://localhost:54329/rest/v1/rpc/reveal_resignation_reason',{headers,data:{p_id:offboarding}});expect(reason.ok()).toBe(false);
 }
 await loginAs(context,'expense');expect((await page.goto('/family-events/'+family+'/edit'))!.status()).toBe(404);const forged=await context.request.post('http://localhost:54329/rest/v1/rpc/publish_family_post',{headers:{Authorization:'Bearer '+tokenFor('expense')},data:{p_id:family,p_version:1,p_publish:true,p_title:'forged',p_body:'forged'}});expect(forged.ok()).toBe(false);
 await loginAs(context,'ceo');expect((await context.request.get('/api/offboarding/documents/ffffffff-ffff-4fff-8fff-ffffffffffff')).status()).toBe(404);await page.goto('/admin/offboarding/'+offboarding);await loginAs(context,'designated');let rejected=false;await page.route('**/admin/**',async route=>{if(!route.request().headers()['next-action'])return route.continue();const response=await route.fetch();const body=await response.text();expect(body).toContain('NEXT_HTTP_ERROR_FALLBACK;404');expect(body).not.toContain(secret);rejected=true;await route.fulfill({response});});await page.getByRole('button',{name:'퇴사 사유 열람'}).click();await expect.poll(()=>rejected).toBe(true);await expect(page.getByRole('button',{name:'퇴사 사유 열람'})).toHaveCount(0);expect(await page.content()).not.toContain(secret);
});
