'use client';
import { useActionState, useId, useState, startTransition, type ReactNode, type FormEvent } from 'react';
import { saveExpense, changeExpenseStatus, importExpenses } from '@/app/actions/expenses';
import { PURPOSES, type Claim, type ExpenseState, type Item, type Purpose } from '@/lib/expenses/types';
import { monthAge, today } from '@/lib/expenses/validation';
function Field({label,children}:{label:string;children:(id:string)=>ReactNode}) {const id=useId();return <div className="field"><label htmlFor={id}>{label}</label>{children(id)}</div>;}
function submit(dispatch:(form:FormData)=>void) {return (event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const button=(event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;if(button?.name)form.set(button.name,button.value);startTransition(()=>dispatch(form));};}
const ErrorMessage=({state}:{state:ExpenseState})=>state.error?<p className="form-error" role="alert">{state.error}</p>:null;
export function ExpenseForm({claim,item,employees,projects}:{claim?:Claim;item?:Item;employees:{id:string;name:string;company_email:string}[];projects:{id:string;name:string}[]}) {
 const [state,action,pending]=useActionState(saveExpense.bind(null,claim?.id||null,item?.id||null),{});
 const [type,setType]=useState<Purpose>(item?.expense_type||'OVERTIME'),[date,setDate]=useState(item?.usage_date||today()),[amount,setAmount]=useState(item?.amount||''),[project,setProject]=useState(item?.project_id||'');
 const [oneWay,setOneWay]=useState(item?.vehicle?.one_way_amount||''),[count,setCount]=useState(item?.vehicle?.trip_count||''),[selected,setSelected]=useState(item?.attendees.map(a=>a.employee_id)||[]);
 const vehicle=type==='FUEL'||type==='TOLL';
 return <form onSubmit={submit(action)} className="expense-entry-form" id="expense-form"><input type="hidden" name="version" value={item?.version||0}/><input type="hidden" name="attachment_id" value={item?.attachment_id||''}/><ErrorMessage state={state}/>
 <Field label="사용일">{id=><input id={id} name="usage_date" type="date" value={date} onChange={e=>setDate(e.target.value)} max={today()} required/>}</Field>
 <Field label="경비 유형">{id=><select id={id} name="expense_type" value={type} onChange={e=>setType(e.target.value as Purpose)}>{Object.entries(PURPOSES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}</Field>
 <div className="field-grid"><Field label="사용처">{id=><input id={id} name="merchant" defaultValue={item?.merchant} maxLength={200} required/>}</Field><Field label="품목 / 사용 목적">{id=><input id={id} name="description" defaultValue={item?.description} maxLength={500} required/>}</Field></div>
 {!vehicle&&<Field label="금액 (원)">{id=><input id={id} name="amount" type="number" min="1" max="1000000000" step="1" value={amount} onChange={e=>setAmount(e.target.value)} required/>}</Field>}
 <Field label="관련 프로젝트">{id=><select id={id} name="project_id" value={project} onChange={e=>setProject(e.target.value)}><option value="">해당 없음</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}</Field>
 <Field label="프로젝트명 / 출장명">{id=><input id={id} name="trip_context" defaultValue={item?.trip_context} maxLength={200} required={vehicle}/>}</Field>
 {vehicle&&<section className="expense-vehicle"><h2>이동 상세</h2><div className="field-grid"><Field label="출발지">{id=><input id={id} name="origin" defaultValue={item?.vehicle?.origin} maxLength={200} required/>}</Field><Field label="도착지">{id=><input id={id} name="destination" defaultValue={item?.vehicle?.destination} maxLength={200} required/>}</Field><Field label="편도 금액 (원)">{id=><input id={id} name="one_way_amount" type="number" min="1" step="1" value={oneWay} onChange={e=>setOneWay(e.target.value)} required/>}</Field><Field label="횟수">{id=><input id={id} name="trip_count" type="number" min="1" max="1000" step="1" value={count} onChange={e=>setCount(e.target.value)} required/>}</Field></div><p>계산 금액 <strong>₩{(Number(oneWay)*Number(count)).toLocaleString('ko-KR')}</strong></p><p className="muted">주유비는 지도 경로, 통행비는 하이패스 영수증을 증빙에 포함해 주세요.</p></section>}
 <div className="field-grid"><Field label="결제수단">{id=><select id={id} name="payment_method" defaultValue={item?.payment_method||'PERSONAL_CARD'}><option value="PERSONAL_CARD">개인카드</option><option value="CASH">현금</option></select>}</Field><Field label="증빙 종류">{id=><select id={id} name="evidence_type" defaultValue={item?.evidence_type||'개인카드'}>{['개인카드','현금영수증','간이영수증'].map(v=><option key={v}>{v}</option>)}</select>}</Field></div>
 {type==='OVERTIME'&&!project&&Number(amount)>10000&&<div className="expense-warning"><strong>지원 기준을 확인해주세요</strong><p>야근식대 기준 10,000원을 초과했습니다. 금액을 확인한 뒤 수정해주세요.</p></div>}
 {type==='DINING'&&<fieldset className="expense-attendees"><legend>참석자 전원 / 월 한도 사용액</legend><p className="muted">참석자를 선택하고 이번 회식에 사용할 월 한도를 입력하세요. 1인 월 누적 30,000원까지 사용할 수 있습니다.</p>{employees.map(e=><div className="attendee-row" key={e.id}><label><input type="checkbox" name="attendees" value={e.id} checked={selected.includes(e.id)} onChange={event=>setSelected(event.target.checked?[...selected,e.id]:selected.filter(v=>v!==e.id))}/>{e.name} <small>{e.company_email}</small></label>{selected.includes(e.id)&&<input aria-label={`${e.name} 한도 사용액`} name={`allocation_${e.id}`} type="number" min="1" max="30000" step="1" defaultValue={item?.attendees.find(a=>a.employee_id===e.id)?.allocated_amount||''} required/>}</div>)}{Number(amount)>selected.length*30000&&selected.length>0&&<p className="expense-warning">참석자 합산 월 지원 기준을 초과했습니다. 확인 후 그대로 제출할 수 있습니다.</p>}</fieldset>}
 <Field label={item?'영수증 / 증빙 변경 (선택)':'영수증 / 증빙 *'}>{id=><div className="expense-upload"><p><strong>카드내역 또는 영수증 PDF를 업로드하세요</strong></p><p>여러 영수증을 하나의 PDF로 합쳐 제출해도 됩니다. PDF / PNG / JPG · 10MB 이하</p><input id={id} name="receipt" type="file" accept="application/pdf,image/png,image/jpeg" required={!item}/>{item&&<a href={`/api/expenses/receipts/${item.attachment_id}`}>현재 증빙 다운로드</a>}</div>}</Field>
 <Field label="비고">{id=><textarea id={id} name="notes" defaultValue={item?.notes} maxLength={2000} rows={2}/>}</Field>
 {(monthAge(date)>=2||claim?.late_reason)&&<Field label="소급 청구 사유">{id=><textarea id={id} name="late_reason" defaultValue={claim?.late_reason} maxLength={2000} required={monthAge(date)>=2}/>}</Field>}
 <button className="button primary" disabled={pending}>{pending?'저장 중…':'저장'}</button>
 </form>;
}
export function ClaimAction({claim,action}:{claim:Claim;action:'SUBMIT'|'LOCK'|'PAY'}) {
 const [state,dispatch,pending]=useActionState(changeExpenseStatus.bind(null,claim.id,action),{});
 return <form onSubmit={submit(dispatch)} className="expense-claim-action"><input type="hidden" name="version" value={claim.version}/><ErrorMessage state={state}/>{action==='SUBMIT'&&<Field label="소급 청구 사유 (2개월 이상 필수)">{id=><textarea id={id} name="late_reason" maxLength={2000} defaultValue={claim.late_reason} required={monthAge(claim.usage_month)>=2}/>}</Field>}<button className="button primary" disabled={pending}>{action==='SUBMIT'?'월 경비 제출':action==='LOCK'?'지급 기간 잠금':'지급 완료 처리'}</button></form>;
}
export function ImportForm() {
 const [state,dispatch,pending]=useActionState(importExpenses,{});const preview=state.preview;
 const errorRows=new Set(preview?.problems.filter(p=>p.severity==='ERROR').map(p=>p.origin||p.code));
 const warningRows=new Set(preview?.problems.filter(p=>p.severity==='WARNING'&&!errorRows.has(p.origin||p.code)).map(p=>p.origin||p.code));
 return <form onSubmit={submit(dispatch)} className="expense-import"><ol className="surface expense-steps"><li>파일 업로드</li><li>자동 검증</li><li className={preview?'active':''}>문제 확인</li><li>등록</li></ol>
 <section className="surface expense-import-input"><div className="field-grid"><Field label="사용월">{id=><input id={id} name="month" type="month" defaultValue={today().slice(0,7)} required/>}</Field><Field label="Excel 파일 (.xlsx)">{id=><input id={id} name="workbook" type="file" accept=".xlsx" required/>}</Field><Field label="차량 사용일 (기존 양식에 날짜가 없는 경우)">{id=><input id={id} name="vehicle_date" type="date"/>}</Field><Field label="전체 경비 증빙 (PDF / PNG / JPG)">{id=><input id={id} name="receipt" type="file" accept="application/pdf,image/png,image/jpeg"/>}</Field></div><Field label="소급 청구 사유">{id=><textarea id={id} name="late_reason" maxLength={2000} rows={2}/>}</Field><button className="button" name="intent" value="preview" disabled={pending}>파일 검증</button></section>
 <ErrorMessage state={state}/>{preview&&<><p><strong>{preview.filename}</strong> · {preview.items.length}개 항목</p><div className="expense-summary"><div className="success"><span>정상</span><strong>{preview.items.filter(i=>!preview.problems.some(p=>p.origin===i.import_origin)).length}건</strong></div><div className="warning"><span>Warning</span><strong>{warningRows.size}건</strong></div><div className="error"><span>Error</span><strong>{errorRows.size}건</strong></div></div><section className="surface table-scroll"><table className="project-table"><thead><tr>{['행 / 시트','사용일','유형','사용처','금액','상태','메시지'].map(s=><th key={s}>{s}</th>)}</tr></thead><tbody>{preview.problems.filter(p=>!p.origin||!preview.items.some(i=>i.import_origin===p.origin)).map((p,n)=><tr key={`global-${n}`}><td>{p.origin||'전체'}</td><td colSpan={4}>—</td><td><span className={`expense-badge ${p.severity.toLowerCase()}`}>{p.severity==='ERROR'?'Error':'Warning'}</span></td><td>{p.message}</td></tr>)}{preview.items.map(i=>{const problems=preview.problems.filter(p=>p.origin===i.import_origin);const severity=problems.some(p=>p.severity==='ERROR')?'error':problems.length?'warning':'success';return <tr key={i.id}><td>{i.import_origin}</td><td>{i.usage_date}</td><td>{PURPOSES[i.expense_type]}</td><td>{i.merchant}</td><td>₩{i.amount.toLocaleString('ko-KR')}</td><td><span className={`expense-badge ${severity}`}>{severity==='error'?'Error':severity==='warning'?'Warning':'정상'}</span></td><td>{problems.map((p,n)=><p key={n}>{p.message}</p>)}</td></tr>;})}</tbody></table></section><div className="heading-row"><p className="muted">Warning은 확인 후 제출할 수 있지만, Error가 있으면 등록할 수 없습니다.</p><button className="button primary" name="intent" value="register" disabled={pending||preview.problems.some(p=>p.severity==='ERROR')}>검증 결과 확인 후 등록</button></div></>}
 </form>;
}
