import Link from 'next/link';
import { notFound } from 'next/navigation';
import { expenseData, expenseDetail, expenseOptions } from '@/lib/expenses/data';
import { PURPOSES, STATUS, type Claim, type Item } from '@/lib/expenses/types';
import { localDate, claimProblems, deadline, editable, itemProblems, today } from '@/lib/expenses/validation';
import type { SearchParams } from '@/lib/employees/data';
import { ClaimAction, ExpenseForm, ImportForm } from './forms';
const money=(v:number)=>`₩${v.toLocaleString('ko-KR')}`;
function Policy(){return <aside className="surface expense-policy"><h2>경비 등록 안내</h2><dl><dt>야근식대</dt><dd>10,000원 초과 시 확인 필요</dd><dt>회식비</dt><dd>월 3만원/인, 참석자 필수</dd><dt>택시비</dt><dd>대표 승인 하에 가능 (회사 정책)</dd><dt>증빙</dt><dd>영수증/PDF 필수</dd><dt>마감</dt><dd>다음 달 첫째 주 주말</dd></dl></aside>;}
function LockPolicy(){return <div className="expense-info"><strong>지급일: 매월 15일</strong><p>지급 기간이 종료되거나 지급·잠금 처리된 경비는 읽기 전용입니다. 별도 승인/반려 기능은 운영하지 않습니다.</p></div>;}
function Badge({claim}:{claim:Claim}){return <span className={`expense-badge ${claim.status==='DRAFT'?'':'success'}`}>{!editable(claim)&&claim.status==='SUBMITTED'?'제출완료 · 잠금':STATUS[claim.status]}</span>;}
export async function ExpenseList({query,admin=false}:{query:SearchParams;admin?:boolean}) {
 const data=await expenseData(admin),options=await expenseOptions();const month=typeof query.month==='string'&&/^\d{4}-(0[1-9]|1[0-2])$/.test(query.month)?query.month:today().slice(0,7);
 const employee=typeof query.employee==='string'?query.employee:'';const status=typeof query.status==='string'?query.status:'';
 const claims=data.claims.filter(c=>c.usage_month.slice(0,7)===month&&(!admin||!employee||c.employee_id===employee)&&(!status||c.status===status)&&(query.validation!=='WARNING'||data.items.some(i=>i.claim_id===c.id&&itemProblems(i,data.items.filter(other=>other.claim_id===c.id)).some(p=>p.severity==='WARNING'))));const ids=new Set(claims.map(c=>c.id));const items=data.items.filter(i=>ids.has(i.claim_id));
 const submitted=claims.filter(c=>c.status!=='DRAFT');const title=admin?'경비 관리':'내 경비';
 return <><div className="page-heading heading-row"><div><h1>{title}</h1><p>{admin?'직원 경비 제출 현황을 확인하고 세무사 전달용 Excel을 다운로드합니다.':'내가 등록한 경비와 이번 달 제출 현황을 확인합니다.'}</p></div>{admin?<a className="button primary" href={`/api/expenses/export?month=${month}&employee=${employee}`}>Excel 다운로드</a>:<Link className="button primary" href="/expenses/new">경비 등록</Link>}</div>
 <div className="expense-summary">{(admin?[['제출 직원',`${new Set(submitted.map(c=>c.employee_id)).size}명`],['미제출',`${options.employees.filter(e=>e.employment_status==='ACTIVE'&&!submitted.some(c=>c.employee_id===e.id)).length}명`],['이번 달 총 경비',money(items.reduce((s,i)=>s+i.amount,0))]]:[['이번 달 제출',money(items.filter(i=>submitted.some(c=>c.id===i.claim_id)).reduce((s,i)=>s+i.amount,0))],['등록 건수',`${items.length}건`],['제출 마감',deadline(month)]]).map(([label,value])=><div className="surface" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
 {!admin&&<div className="expense-warning"><strong>{month} 사용 경비 · {deadline(month)} 제출 마감</strong><p>마감 이후에도 제출할 수 있습니다. 2개월 이상 소급 청구 시 사유를 입력해 주세요.</p></div>}
 <form className="surface expense-filters"><label>사용월<input name="month" type="month" defaultValue={month}/></label>{admin&&<label>직원<select name="employee" defaultValue={employee}><option value="">전체 직원</option>{options.employees.map(e=><option value={e.id} key={e.id}>{e.name}</option>)}</select></label>}<label>상태<select name="status" defaultValue={status}><option value="">전체</option>{Object.entries(STATUS).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>검증 상태<select name="validation" defaultValue={query.validation==='WARNING'?'WARNING':''}><option value="">전체</option><option value="WARNING">Warning 있음</option></select></label><button className="button">조회</button></form>
 <section className="surface table-scroll expense-list-table">{admin?<table className="project-table"><thead><tr>{['직원','사용월','제출일','건수','금액','Warning','수정 가능','상태','관리'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{options.employees.filter(e=>!employee||e.id===employee).map(e=>{const c=claims.find(c=>c.employee_id===e.id),list=items.filter(i=>i.claim_id===c?.id);if(!c&&(status||query.validation==='WARNING'))return null;return <tr key={e.id}><td><strong>{e.name}</strong></td><td>{month}</td><td>{c?.submitted_at?localDate(c.submitted_at):'—'}</td><td>{list.length||'—'}</td><td>{money(list.reduce((s,i)=>s+i.amount,0))}</td><td>{list.reduce((s,i)=>s+itemProblems(i,list).filter(p=>p.severity==='WARNING').length,0)}</td><td>{c?.payment_date?`${c.payment_date}까지`:'지급 전'}</td><td>{c?<Badge claim={c}/>:<span className="expense-badge warning">미제출</span>}</td><td>{c&&<Link href={`/admin/expenses/${c.id}`}>보기</Link>}</td></tr>;})}</tbody></table>:items.length?<table className="project-table"><thead><tr>{['사용일','구분','사용처','금액','프로젝트/출장','증빙','상태','관리'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{items.map(i=>{const c=claims.find(c=>c.id===i.claim_id)!;return <tr key={i.id}><td>{i.usage_date}</td><td>{PURPOSES[i.expense_type]}</td><td><strong>{i.merchant}</strong></td><td>{money(i.amount)}</td><td>{i.trip_context||options.projects.find(p=>p.id===i.project_id)?.name||'—'}</td><td><a href={`/api/expenses/receipts/${i.attachment_id}`}>증빙</a></td><td><Badge claim={c}/></td><td><Link href={`/expenses/${c.id}`}>보기</Link></td></tr>;})}</tbody></table>:<div className="empty-state"><h2>이번 달 등록한 경비가 없습니다</h2><p>직접 등록하거나 공식 Excel 템플릿으로 가져오세요.</p><Link className="button" href="/expenses/upload">Excel 업로드</Link></div>}</section>
 {!admin&&claims.map(c=><div className="expense-month-link" key={c.id}><Link href={`/expenses/${c.id}`}>{month} 월 경비 상세 / 제출</Link></div>)}<LockPolicy/></>;
}
export async function ExpenseEditor({id,query}:{id?:string;query:SearchParams}) {
 const options=await expenseOptions();let claim:Claim|undefined,item:Item|undefined;
 if(id){const claimId=typeof query.claim==='string'?query.claim:'';const detail=await expenseDetail(claimId);claim=detail.claim;item=detail.items.find(i=>i.id===id);if(!item||!editable(claim))notFound();}
 return <><div className="page-heading"><h1>{item?'경비 수정':'경비 등록'}</h1><p>개인카드로 사용한 경비를 직접 등록합니다.</p></div>{!options.selfId?<section className="surface empty-state"><h2>직원 계정 연결이 필요합니다</h2><p>관리자에게 직원 프로필과 로그인 계정 연결을 요청해 주세요.</p></section>:<div className="expense-entry-layout"><section className="surface"><ExpenseForm claim={claim} item={item} employees={options.employees.filter(e=>e.employment_status==='ACTIVE')} projects={options.projects}/></section><Policy/></div>}</>;
}
export async function ExpenseDetail({id,query,admin=false}:{id:string;query:SearchParams;admin?:boolean}) {
 const {claim,items,attachments}=await expenseDetail(id,admin),options=await expenseOptions();const person=options.employees.find(e=>e.id===claim.employee_id);
 const problems=[...claimProblems(claim.usage_month,claim.late_reason,claim.submitted_at?localDate(claim.submitted_at):undefined),...items.flatMap(i=>itemProblems(i,items))];
 return <><div className="page-heading heading-row"><div><h1>{claim.usage_month.slice(0,7)} 경비 상세</h1><p>{person?.name} · 합계 {money(items.reduce((s,i)=>s+i.amount,0))} · <Badge claim={claim}/></p></div><Link className="button" href={`${admin?'/admin':''}/expenses?month=${claim.usage_month.slice(0,7)}`}>목록</Link></div>{query.saved&&<p className="success-banner" role="status">저장했습니다.</p>}
 {problems.map((p,n)=><div key={n} className={p.severity==='ERROR'?'form-error':'expense-warning'}><strong>{p.severity==='ERROR'?'Error':'Warning'}</strong><p>{p.message}</p></div>)}
 {items.map(i=><section className="surface expense-item-card" key={i.id}><div className="heading-row"><div><h2>{PURPOSES[i.expense_type]} · {i.merchant}</h2><p>{i.usage_date} · {i.description}</p></div><strong>{money(i.amount)}</strong></div><p>{i.payment_method==='PERSONAL_CARD'?'개인카드':'현금'} · {i.evidence_type} {admin&&`· ${i.account_category}`}</p>{i.trip_context&&<p>프로젝트/출장: {i.trip_context}</p>}{i.vehicle&&<p>{i.vehicle.origin} → {i.vehicle.destination} · {money(i.vehicle.one_way_amount)} × {i.vehicle.trip_count}회 = {money(i.amount)}</p>}{i.attendees.length>0&&<p>참석자: {i.attendees.map(a=>`${options.employees.find(e=>e.id===a.employee_id)?.name||a.employee_id} (${money(a.allocated_amount)})`).join(', ')}</p>}{i.notes&&<p className="preserve-lines">{i.notes}</p>}{i.import_filename&&<p className="muted">{i.import_filename} · {i.import_origin}</p>}<div className="heading-row"><a href={`/api/expenses/receipts/${i.attachment_id}`}>{attachments.find(a=>a.id===i.attachment_id)?.filename||'증빙'} 다운로드</a>{!admin&&editable(claim)&&<Link className="button" href={`/expenses/items/${i.id}/edit?claim=${claim.id}`}>수정</Link>}</div></section>)}
 <section className="surface expense-item-card"><h2>제출 / 지급 내역</h2><p>제출일: {claim.submitted_at?localDate(claim.submitted_at):'미제출'} · 지급 예정일: {claim.payment_date||'제출 시 결정'} · 잠금일: {claim.locked_at?localDate(claim.locked_at):'—'}</p>{claim.late_reason&&<p>소급 사유: {claim.late_reason}</p>}{!admin&&editable(claim)&&items.length>0&&<ClaimAction claim={claim} action="SUBMIT"/>}{admin&&claim.status==='SUBMITTED'&&<ClaimAction claim={claim} action="LOCK"/>}{admin&&['SUBMITTED','LOCKED'].includes(claim.status)&&<ClaimAction claim={claim} action="PAY"/>}{!editable(claim)&&<p className="expense-info">지급 기간이 잠겼습니다. 경비와 증빙은 읽기 전용입니다.</p>}</section><LockPolicy/></>;
}
export function ExpenseImport(){return <><div className="page-heading heading-row"><div><h1>Excel 업로드</h1><p>공식 경비 템플릿을 업로드하고 등록 전 검증 결과를 확인합니다.</p></div><a className="button primary" download href="/api/expenses/template">템플릿 다운로드</a></div><ImportForm/></>;}
