import Link from 'next/link';
import { notFound } from 'next/navigation';
import { can,type Principal } from '@/lib/permissions';
import { employeeClient,type SearchParams } from '@/lib/employees/data';
import { assets } from '@/lib/assets/data';
import { operationCases,operationDetail,operationPeople,resignationDocuments,announcements,announcement,familyPosts,familyRegistrations,familyRegistration,birthdayTemplate,readRows } from '@/lib/operations/data';
import { TASK_LABELS,TASK_STATES,EVENT_CATEGORIES,type OperationKind } from '@/lib/operations/types';
import { OperationStart,TaskEditor,CaseControls,ResignationReason,ResignationUpload,AnnouncementEditor,FamilyEditor,FamilyPublication,BirthdayEditor } from './forms';
function Heading({title,description,href,action}:{title:string;description:string;href?:string;action?:string}){return <div className="heading-row"><div className="page-heading"><h1>{title}</h1><p>{description}</p></div>{href&&<Link className="button primary" href={href}>{action}</Link>}</div>;}
function Saved({query}:{query:SearchParams}){return query.saved?<p className="success-banner" role="status">저장했습니다.</p>:null;}
function Badge({children,done=false}:{children:React.ReactNode;done?:boolean}){return <span className={`operation-badge ${done?'done':''}`}>{children}</span>;}
const date=(value:string)=>new Date(value).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'});
export async function OperationsScreen({kind,id,create=false,query,principal}:{kind:OperationKind;id?:string;create?:boolean;query:SearchParams;principal:Principal}){
 const records=await operationCases(kind),people=await operationPeople(),base='/admin/'+kind;
 if(create)return <><Heading title={kind==='onboarding'?'온보딩 시작':'퇴사 등록'} description="기존 직원 정보를 연결하고 처리 항목을 관리합니다."/><OperationStart kind={kind} people={people.filter(p=>!records.some(r=>r.employee_id===p.id))}/></>;
 const selected=id||records.filter(r=>!r.completed_at)[0]?.id||records[0]?.id;
 const detail=selected?await operationDetail(kind,selected):null,record=detail?.record,person=people.find(p=>p.id===record?.employee_id),name=(id:string)=>people.find(p=>p.id===id)?.name||'—';
 const orderedTasks=detail?.tasks.toSorted((a,b)=>Object.keys(TASK_LABELS).indexOf(a.type)-Object.keys(TASK_LABELS).indexOf(b.type))||[];
 const task=typeof query.task==='string'?orderedTasks.find(t=>t.id===query.task):undefined;if(query.task&&!task)notFound();
 const devices=kind==='offboarding'&&record?(await assets()).filter(a=>a.current_holder_id===record.employee_id):[];
 const sensitive=kind==='offboarding'&&record&&can(principal,'RESIGNATION_REASON_ACCESS');
 const documents=sensitive?await resignationDocuments(record.id):[];
 const reasonVersion=sensitive?(await readRows<{case_id:string;version:number}>('resignation_private','case_id,version',{case_id:record.id},'case_id'))[0]?.version||0:0;
 return <><Heading title={kind==='onboarding'?'온보딩':'퇴사 관리'} description={kind==='onboarding'?'신규 입사자의 필수 준비 항목과 담당자를 관리합니다.':'퇴사일, 사직서, 미사용 연차 확인 후 직원 상태를 INACTIVE로 전환합니다.'} href={base+'/new'} action={kind==='onboarding'?'입사자 등록':'퇴사 등록'}/><Saved query={query}/>
 {records.length>0&&<nav className="operation-picker" aria-label="직원별 처리 내역">{records.map(r=><Link key={r.id} href={`${base}/${r.id}`} aria-current={r.id===selected?'page':undefined}>{name(r.employee_id)} · {r.completed_at?'완료':'진행중'}</Link>)}</nav>}
 {!record?<section className="surface empty-state"><h2>{kind==='onboarding'?'등록된 온보딩이 없습니다':'등록된 퇴사 처리가 없습니다'}</h2><p>직원을 선택하여 체크리스트를 시작하세요.</p></section>:<>
 <section className="surface operation-person"><div className="heading-row"><h2>{person?.name}</h2><Badge done={Boolean(record.completed_at)}>{record.completed_at?'처리 완료':kind==='onboarding'?'준비중':'퇴사 예정'}</Badge></div><p className="muted">입사일 {person?.hire_date} · {person?.title} · {person?.employment_status}</p>{kind==='offboarding'&&<dl><div><dt>퇴사일</dt><dd>{record.resignation_date}</dd></div><div><dt>사직서</dt><dd>{record.document_received?'수령 완료':'미수령'}</dd></div><div><dt>미사용 연차 확인</dt><dd>{record.unused_leave_checked?'확인 완료':'확인 필요'}</dd></div><div><dt>최종 상태</dt><dd>{record.completed_at?'INACTIVE':'재직 → INACTIVE'}</dd></div></dl>}</section>
 {devices.length>0&&<aside className="asset-notice warning"><strong>미반납 장비 {devices.length}대</strong><p>{devices.map(a=><Link key={a.id} href={`/admin/assets/${a.id}`}>{a.model||a.serial_number} · {a.serial_number}　</Link>)}</p><p>운영 참고 사항이며 퇴사 처리를 차단하지 않습니다.</p></aside>}
 <section className="operation-table-wrap"><table className="asset-table operation-table"><thead><tr>{['항목','상태','담당자','메모','관리'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{orderedTasks.map(t=><tr key={t.id}><td><strong>{TASK_LABELS[t.type]}</strong></td><td><Badge done={t.status==='DONE'}>{TASK_STATES[t.status]}</Badge></td><td>{detail?.owners.filter(o=>o.task_id===t.id).map(o=>name(o.employee_id)).join(', ')||'미지정'}</td><td className="operation-memo" title={t.memo}>{t.memo||'—'}</td><td>{!record.completed_at&&<Link href={`${base}/${record.id}?task=${t.id}`}>수정</Link>}</td></tr>)}</tbody></table></section>
 {task&&!record.completed_at&&<TaskEditor key={`${task.id}:${task.version}`} kind={kind} task={task} owners={detail!.owners.filter(o=>o.task_id===task.id).map(o=>o.employee_id)} people={people}/>}
 <aside className="asset-notice"><strong>{kind==='onboarding'?'한 항목에 여러 담당자를 지정할 수 있습니다.':'대표자 전용 정보'}</strong><p>{kind==='onboarding'?'직원 등록 후 온보딩을 시작합니다. 계정 자동 생성 기능은 제공하지 않습니다.':'사직서와 퇴사 사유는 대표자만 열람할 수 있습니다. 직원 데이터는 삭제하지 않고 INACTIVE 상태로 보관합니다.'}</p>{kind==='onboarding'&&<p><Link href={'/admin/assets?q='+encodeURIComponent(person?.name||'')}>기존 장비 확인</Link> · <Link href="/admin/accounts">기존 업무 계정 확인</Link></p>}</aside>
 <CaseControls key={`${record.id}:${record.version}`} record={record}/>
 {sensitive&&<><ResignationReason key={`${record.id}:${reasonVersion}`} id={record.id}/><section className="surface operations-form"><h2>대표자 전용 · 사직서</h2>{documents.map(d=><a key={d.id} href={`/api/offboarding/documents/${d.id}`}>{d.filename} 다운로드</a>)}<ResignationUpload id={record.id}/></section></>}
 <details className="surface operation-history"><summary>처리 이력</summary><ol>{detail?.history.map(h=><li key={h.id}>{date(h.occurred_at)} · {{START:'시작',TASK_UPDATE:'항목 변경',UPDATE:'정보 변경',COMPLETE:'처리 완료'}[h.action]||h.action}{h.status&&` · ${h.previous_status?TASK_STATES[h.previous_status as keyof typeof TASK_STATES]+' → ':''}${TASK_STATES[h.status as keyof typeof TASK_STATES]}`}{h.owner_ids?.length?` · ${h.owner_ids.map(name).join(', ')}`:''}</li>)}</ol></details>
 </>}</>;
}
export async function AnnouncementsScreen({id,edit=false,create=false,query,principal}:{id?:string;edit?:boolean;create?:boolean;query:SearchParams;principal:Principal}){
 const manage=can(principal,'ANNOUNCEMENT_MANAGE');if((edit||create)&&!manage)notFound();const record=id?await announcement(id):undefined;
 if(create||edit)return <><Heading title={create?'공지 등록':'공지 수정'} description="회사 구성원에게 안내할 내용을 작성합니다."/><AnnouncementEditor record={record}/></>;
 if(record)return <><Heading title="공지사항" description="회사에서 공유하는 주요 안내를 확인합니다." href={manage?`/announcements/${id}/edit`:undefined} action="공지 수정"/><Saved query={query}/><article className="surface board-detail"><h2>{record.title}</h2><p className="muted">{record.author_name} · {record.published_at?date(record.published_at):'초안'}</p><div className="prose-body">{record.body}</div></article><Link className="button" href="/announcements">목록으로</Link></>;
 const rows=(await announcements()).toSorted((a,b)=>(b.published_at||'').localeCompare(a.published_at||''));return <><Heading title="공지사항" description="회사에서 공유하는 주요 안내를 확인합니다." href={manage?'/announcements/new':undefined} action="공지 등록"/><section className="company-board">{rows.length?rows.map(r=><Link className="board-row" href={`/announcements/${r.id}`} key={r.id}><div><h2>{r.title}{!r.published_at&&<Badge>초안</Badge>}</h2><p>{r.body}</p></div><small>{r.author_name} · {r.published_at?date(r.published_at):'미게시'}</small></Link>):<div className="empty-state"><h2>게시된 공지사항이 없습니다</h2></div>}</section><p className="muted">읽음 확인이나 전체메일 발송 기능은 사용하지 않습니다.</p></>;
}
function FamilyGuide(){return <aside className="surface event-guide"><h2>지원 유형</h2>{Object.values(EVENT_CATEGORIES).map(c=><strong key={c}>{c}</strong>)}<h3>경조휴가</h3><p className="muted">연차와 별도인 경조휴가입니다. 현재 휴가 시스템을 이용해 주세요. 이 화면에서는 휴가가 생성되지 않습니다.</p></aside>;}
export async function FamilyScreen({id,create=false,edit=false,review=false,query,principal}:{id?:string;create?:boolean;edit?:boolean;review?:boolean;query:SearchParams;principal:Principal}){
 const people=await operationPeople(),person=(id:string)=>people.find(p=>p.id===id)?.name||'—';
 if(create||edit){const registration=id?await familyRegistration(id):undefined;const posts=registration?await familyPosts():[];const {data:own}=await(await employeeClient()).rpc('current_employee_id');if(!own) return <section className="surface empty-state"><h1>직원 정보 연결이 필요합니다</h1><p>관리자에게 계정과 직원 정보 연결을 요청해 주세요.</p></section>;
 const notification=registration?await(await employeeClient()).rpc('family_notification_status',{p_id:registration.id}):null;
 return <><Heading title={registration?'내 경조사 등록':'경조사 등록'} description="경조사 소식을 등록하고 대표자에게 대응 요청 메일을 보냅니다."/><Saved query={query}/>{registration&&<p className="asset-notice">대표자 알림: {notification?.data==='SENT'?'발송 완료':notification?.data==='REVIEW'?'발송 확인 필요 · 관리자에게 문의해 주세요':'발송 대기 · 메일 연결 상태에 따라 처리됩니다'}</p>}<div className="operations-columns"><FamilyEditor key={registration?.version||0} record={registration} name={person(own)}/><FamilyGuide/></div>{registration&&<FamilyPublication key={posts.find(p=>p.registration_id===registration.id)?.version||0} id={registration.id} post={posts.find(p=>p.registration_id===registration.id)}/>}</>;
 }
 if(review){const rows=await familyRegistrations(true);if(id){const r=await familyRegistration(id,true);return <><Heading title="대표자 경조사 접수" description="회사 대응을 위한 비공개 등록 내용입니다."/><article className="surface board-detail"><Badge>{EVENT_CATEGORIES[r.category]}</Badge><h2>{r.title}</h2><p>{person(r.employee_id)} · {r.event_date}</p><div className="prose-body">{r.details}</div></article></>;}
 return <><Heading title="대표자 경조사 접수" description="등록자와 대표자만 조회할 수 있습니다."/><section className="company-board">{rows.map(r=><Link key={r.id} className="board-row" href={`/family-events/review/${r.id}`}><h2>{r.title}</h2><small>{person(r.employee_id)} · {r.event_date}</small></Link>)}{!rows.length&&<p className="empty-state">접수된 경조사가 없습니다.</p>}</section></>;}
 const posts=await familyPosts(),own=await familyRegistrations();return <><Heading title="경조사" description="경조사 소식을 등록하고 회사 구성원에게 공유합니다." href="/family-events/new" action="경조사 등록"/><aside className="asset-notice"><strong>경조사 등록 시 대표자에게 이메일이 발송됩니다.</strong><p>회사 대응을 위한 비공개 등록과 게시판 공유는 별도로 관리됩니다.</p></aside><section className="company-board family-board">{posts.length?posts.toSorted((a,b)=>b.event_date.localeCompare(a.event_date)).map(p=><article className="board-row" key={p.registration_id}><div><h2><Badge>{EVENT_CATEGORIES[p.category]}</Badge> {person(p.employee_id)} · {p.title}</h2><div className="prose-body">{p.body}</div></div><small>{p.event_date}</small></article>):<div className="empty-state"><h2>공유된 경조사 소식이 없습니다</h2></div>}</section><section className="surface family-leave"><div><h2>경조휴가 안내</h2><p className="muted">DXT 사칙에 따라 연차와 별도로 신청합니다. 현재 휴가 시스템을 이용해 주세요.</p></div><button className="button" disabled title="휴가 기능은 이번 단계에서 제공하지 않습니다">경조휴가 신청 · 준비중</button></section><section className="surface operations-form"><h2>내 등록 내역 (비공개)</h2>{own.map(r=><Link key={r.id} href={`/family-events/${r.id}/edit`}>{r.title} · {r.event_date}</Link>)}{!own.length&&<p className="muted">등록한 경조사가 없습니다.</p>}{can(principal,'FAMILY_EVENT_REVIEW')&&<Link className="button" href="/family-events/review">대표자 접수함</Link>}</section></>;
}
export async function BirthdayScreen({query}:{query:SearchParams}){const current=Number(new Intl.DateTimeFormat('en',{timeZone:'Asia/Seoul',year:'numeric'}).format(new Date())),year=typeof query.year==='string'&&/^[1-9]\d{3}$/.test(query.year)&&Number(query.year)>=1900?Number(query.year):current,record=await birthdayTemplate(year);return <><Heading title="생일 메일" description="생일 당일 오전 9시에 본인에게 발송되는 축하 메일 템플릿을 관리합니다."/><Saved query={query}/><aside className="asset-notice"><strong>자동 발송 규칙</strong><p>생일 당일 오전 9시 (한국 시간) · 생일자 본인에게만 발송 · 음력 생일은 지원하지 않음</p></aside><form className="birthday-year"><label htmlFor="template-year">템플릿 연도</label><input id="template-year" name="year" type="number" min={1900} max={9999} defaultValue={year}/><button className="button">연도 선택</button></form><BirthdayEditor key={`${year}:${record?.version||0}`} year={year} record={record}/></>;}
