import Link from 'next/link';
import { notFound } from 'next/navigation';
import { assets,assetRecord,assetEmployees,vaultEntries } from '@/lib/assets/data';
import { ASSET_TYPES,ASSET_STATUSES,ASSIGNMENT_COLUMNS,EVENT_COLUMNS,vaultPath,revealCapability,type VaultKind,type Asset } from '@/lib/assets/types';
import { employeeClient,type SearchParams } from '@/lib/employees/data';
import { can,type Principal } from '@/lib/permissions';
import { AssetForm,VaultForm,RevealSecret,DeleteAsset } from './forms';
function Heading({title,description,href,action}:{title:string;description:string;href?:string;action?:string}){return <div className="heading-row"><div className="page-heading"><h1>{title}</h1><p>{description}</p></div>{href&&<Link className="button primary" href={href}>{action}</Link>}</div>;}
function Notice({title,children,warning=false}:{title:string;children:React.ReactNode;warning?:boolean}){return <aside className={`asset-notice${warning?' warning':''}`}><strong>{title}</strong><p>{children}</p></aside>;}
function Badge({status}:{status:Asset['status']}){return <span className={`asset-badge ${status}`}>{ASSET_STATUSES[status]}</span>;}
const date=(v:string|null)=>v?new Date(v).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'}):'—';
export async function AssetList({query,own=false,id}:{query:SearchParams;own?:boolean;id?:string}){
 const all=own&&id?[await assetRecord(id,true)]:await assets(own),employees=own?[]:await assetEmployees(),person=(id:string|null)=>employees.find(e=>e.id===id);
 if(own)return <><Heading title="내 장비" description="현재 나에게 지급된 회사 장비를 확인합니다."/>{all.length?all.map(a=><section className="asset-card" key={a.id}><div className="heading-row"><span className="asset-type">{ASSET_TYPES[a.type]}</span><Badge status={a.status}/></div><h2>{a.model||ASSET_TYPES[a.type]}</h2><dl><div><dt>Serial Number</dt><dd>{a.serial_number}</dd></div><div><dt>지급일</dt><dd>{date(a.assigned_at)}</dd></div></dl></section>):<section className="surface empty-state"><h2>지급된 장비가 없습니다</h2><p>장비 지급이 필요하면 IT 관리자에게 문의해 주세요.</p></section>}<Notice title="장비 정보가 실제와 다르면 IT 관리자에게 알려주세요.">직원 화면에서는 본인에게 현재 할당된 장비만 조회할 수 있습니다.</Notice></>;
 const q=typeof query.q==='string'?query.q.slice(0,100):'',rows=all.filter(a=>(!query.type||a.type===query.type)&&(!query.status||a.status===query.status)&&`${a.model} ${a.serial_number} ${person(a.current_holder_id)?.name||''}`.toLowerCase().includes(q.toLowerCase()));
 return <><Heading title="장비 관리" description="회사 보유 장비의 현재 보유자와 상태를 관리합니다." href="/admin/assets/new" action="장비 등록"/><div className="asset-summary">{[['사용중',['IN_USE']],['보유',['AVAILABLE']],['수리/분실',['REPAIR','LOST']]].map(([label,statuses])=><section key={String(label)}><span>{label}</span><strong>{all.filter(a=>statuses.includes(a.status)).length}대</strong></section>)}</div><form className="asset-filters"><select aria-label="유형 필터" name="type" defaultValue={typeof query.type==='string'?query.type:''}><option value="">전체 유형</option>{Object.entries(ASSET_TYPES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="상태 필터" name="status" defaultValue={typeof query.status==='string'?query.status:''}><option value="">전체 상태</option>{Object.entries(ASSET_STATUSES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input aria-label="모델/SN/보유자 검색" name="q" placeholder="모델/SN/보유자 검색" defaultValue={q}/><button className="button">검색</button></form><div className="asset-table-wrap"><table className="asset-table"><thead><tr>{['유형','모델','S/N','현재 보유자','상태','지급일','관리'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{ASSET_TYPES[a.type]}</td><td><strong>{a.model||'—'}</strong></td><td>{a.serial_number}</td><td>{person(a.current_holder_id)?.name||'—'}{person(a.current_holder_id)?.employment_status==='INACTIVE'&&<small className="field-error">퇴사 · 미반납</small>}</td><td><Badge status={a.status}/></td><td>{date(a.assigned_at)}</td><td><Link href={`/admin/assets/${a.id}`}>보기</Link></td></tr>)}</tbody></table>{!rows.length&&<p className="empty-state">조건에 맞는 장비가 없습니다.</p>}</div><Notice title="관리 대상: 노트북 · 데스크탑 · 모니터 · 외장하드">별도 DXT 자산번호 없이 제조사 Serial Number를 장비 식별 기준으로 사용합니다.</Notice></>;
}
export async function AssetEditor({id,query}:{id?:string;query:SearchParams}){
 const asset=id?await assetRecord(id):undefined,employees=await assetEmployees();
 const db=await employeeClient();const assignments=id?await db.from('asset_assignment').select(ASSIGNMENT_COLUMNS).eq('asset_id',id).order('assigned_at',{ascending:false}):null;
 const events=id?await db.from('asset_event').select(EVENT_COLUMNS).eq('asset_id',id).order('occurred_at',{ascending:false}):null;
 if(assignments?.error||events?.error)throw new Error('장비 이력을 불러오지 못했습니다.');const name=(id:string|null)=>employees.find(e=>e.id===id)?.name||'—';
 return <><Heading title={asset?'장비 상세':'장비 등록'} description="장비 정보와 지급·반납 이력을 관리합니다."/>{query.saved&&<p role="status" className="success-banner">저장했습니다.</p>}<AssetForm asset={asset} employees={employees}/>{asset&&<><section className="surface"><h2>지급 이력</h2><table className="asset-table"><thead><tr><th>보유자</th><th>지급일</th><th>반납일</th></tr></thead><tbody>{assignments?.data?.map(a=><tr key={a.id}><td>{name(a.employee_id)}</td><td>{date(a.assigned_at)}</td><td>{a.returned_at?date(a.returned_at):'현재 보유'}</td></tr>)}</tbody></table>{!assignments?.data?.length&&<p>지급 이력이 없습니다.</p>}</section><section className="surface"><h2>상태·보유자 변경 이력</h2><ul className="asset-history">{events?.data?.map(e=><li key={e.id}>{date(e.occurred_at)} · {e.previous_status?ASSET_STATUSES[e.previous_status as Asset['status']]:'등록'} → {ASSET_STATUSES[e.status as Asset['status']]} · {name(e.previous_holder_id)} → {name(e.holder_id)}</li>)}</ul></section><DeleteAsset kind="asset" id={asset.id} version={asset.version}/></>}</>;
}
export async function VaultScreen({kind,principal,id,create=false,query}:{kind:VaultKind;principal:Principal;id?:string;create?:boolean;query:SearchParams}){
 const entries=await vaultEntries(kind),entry=id?entries.find(e=>e.id===id):undefined;if(id&&!entry)notFound();const devices=kind==='windows'?await assets():[],employees=kind==='windows'?await assetEmployees():[],path=vaultPath(kind),title=kind==='windows'?'Windows 라이선스':'계정 관리';
 if(create||entry)return <><Heading title={create?(kind==='windows'?'라이선스 등록':'계정 등록'):title+' 상세'} description="비밀값은 기본적으로 숨겨져 있습니다."/>{query.saved&&<p className="success-banner" role="status">저장했습니다.</p>}{entry&&can(principal,revealCapability(kind))&&<section className="surface"><h2>{kind==='windows'?'제품키':'비밀번호'} 확인</h2><RevealSecret key={`${entry.id}:${entry.version}`} kind={kind} id={entry.id}/></section>}<VaultForm kind={kind} entry={entry} assets={devices} employees={employees}/>{entry&&<DeleteAsset kind={kind} id={entry.id} version={entry.version}/>}</>;
 return <><Heading title={title} description={kind==='windows'?'Windows 제품키와 할당 장비를 안전하게 관리합니다.':'사내 공용 및 업무용 서비스 로그인 정보를 관리합니다.'} href={`${path}/new`} action={kind==='windows'?'라이선스 등록':'계정 등록'}/><Notice title={kind==='windows'?'제품키는 기본적으로 마스킹되며 권한이 있는 사용자만 전체 값을 확인할 수 있습니다.':'비밀번호는 기본 마스킹 처리하고, 권한이 있는 사용자만 보기 버튼으로 확인합니다.'}>{kind==='windows'?'비용·갱신일·SaaS 구독 관리는 이 화면에서 다루지 않습니다.':'비밀번호는 별도 암호화 필드로 저장합니다.'}</Notice><div className="asset-table-wrap vault-table"><table className="asset-table"><thead><tr>{(kind==='windows'?['Edition','장비','S/N','사용자','Product Key','관리']:['서비스','로그인 ID','비밀번호','URL','비고','관리']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{entries.map(e=>{const device=devices.find(a=>a.id===e.device_asset_id);return <tr key={e.id}><td><strong>{e.name}</strong></td>{kind==='windows'?<><td>{device?.model||'—'}</td><td>{device?.serial_number||'—'}</td><td>{employees.find(p=>p.id===e.assigned_employee_id)?.name||'—'}</td><td className="masked-key">•••••-•••••-•••••-•••••-{e.key_suffix}</td></>:<><td>{e.login_id}</td><td>••••••••••</td><td>{e.url?<a href={e.url} target="_blank" rel="noreferrer">{new URL(e.url).hostname}</a>:'—'}</td><td className="asset-memo" title={e.memo}>{e.memo||'—'}</td></>}<td><Link href={`${path}/${e.id}`}>보기</Link></td></tr>;})}</tbody></table>{!entries.length&&<p className="empty-state">등록된 {kind==='windows'?'라이선스':'계정'}가 없습니다.</p>}</div>{kind==='windows'&&<Notice warning title="보안 원칙">제품키는 암호화하여 저장합니다. 전체 값은 권한을 확인한 뒤 별도 보기 기능으로 제공합니다.</Notice>}</>;
}
