'use server';
import { randomUUID } from 'node:crypto';
import { redirect,notFound } from 'next/navigation';
import { revalidatePath } from 'next/cache';
import { requireCapability } from '@/lib/auth/access';
import { employeeClient } from '@/lib/employees/data';
import { isUuid,versionFrom,ValidationError } from '@/lib/employees/validation';
import { encryptHr,decryptHr } from '@/lib/employees/crypto-server';
import { field,uuid,dateInput,taskInput,familyInput,templateInput } from '@/lib/operations/validation';
import { operationCapability,type OperationKind } from '@/lib/operations/types';
import { runCompanyMail } from '@/lib/operations/mail-server';
import type { FormState } from '@/lib/employees/types';
function assertId(id:string){if(!isUuid(id))notFound();}
function assertKind(kind:string):asserts kind is OperationKind{if(kind!=='onboarding'&&kind!=='offboarding')notFound();}
function failure(error:unknown):FormState{if(error instanceof ValidationError)return {error:error.message,fields:error.fields};if(error&&typeof error==='object'&&'code' in error&&error.code==='40001')return {error:'다른 사용자가 변경했습니다. 새로고침 후 다시 시도해 주세요.'};return {error:'저장하지 못했습니다. 필수 항목과 처리 상태를 확인하고 새로고침 후 다시 시도해 주세요.'};}
async function rpc(name:string,args:Record<string,unknown>){const {data,error}=await(await employeeClient()).rpc(name,args);if(error)throw error;return data;}
export async function startOperation(kind:OperationKind,_state:FormState,form:FormData):Promise<FormState>{assertKind(kind);await requireCapability(operationCapability(kind));const id=randomUUID();try{await rpc('start_operation',{p_id:id,p_kind:kind,p_employee:uuid(form,'employee_id'),p_date:kind==='offboarding'?dateInput(form,'resignation_date'):null});}catch(error){return failure(error);}revalidatePath('/admin/'+kind);redirect(`/admin/${kind}/${id}?saved=1`);}
export async function saveTask(kind:OperationKind,caseId:string,id:string,_state:FormState,form:FormData):Promise<FormState>{assertKind(kind);await requireCapability(operationCapability(kind));assertId(id);assertId(caseId);try{await rpc('save_operation_task',{p_id:id,...taskInput(form),p_version:versionFrom(form)});}catch(error){return failure(error);}revalidatePath(`/admin/${kind}/${caseId}`);redirect(`/admin/${kind}/${caseId}?saved=1`);}
export async function saveCase(kind:OperationKind,id:string,_state:FormState,form:FormData):Promise<FormState>{assertKind(kind);await requireCapability(operationCapability(kind));assertId(id);try{await rpc('save_operation_case',{p_id:id,p_date:kind==='offboarding'?dateInput(form,'resignation_date'):null,p_leave:form.get('unused_leave_checked')==='on',p_complete:form.get('complete')==='yes',p_version:versionFrom(form)});}catch(error){return failure(error);}revalidatePath('/admin/'+kind);revalidatePath('/people');revalidatePath('/admin/assets');redirect(`/admin/${kind}/${id}?saved=1`);}
export async function revealResignation(id:string):Promise<{value?:string;version?:number;error?:string}>{await requireCapability('RESIGNATION_REASON_ACCESS');assertId(id);try{const data=await rpc('reveal_resignation_reason',{p_id:id});return {value:data.ciphertext?decryptHr(data.ciphertext,`${id}:resignation`):'',version:data.version};}catch{return {error:'퇴사 사유를 열람하지 못했습니다.'};}}
export async function saveResignationReason(id:string,_state:FormState,form:FormData):Promise<FormState>{await requireCapability('RESIGNATION_REASON_ACCESS');assertId(id);try{const reason=field(form,'reason',5000);await rpc('save_resignation_reason',{p_id:id,p_ciphertext:encryptHr(reason,`${id}:resignation`),p_version:versionFrom(form)});}catch(error){return failure(error);}revalidatePath('/admin/offboarding/'+id);redirect(`/admin/offboarding/${id}?saved=1`);}
export async function uploadResignation(id:string,_state:FormState,form:FormData):Promise<FormState>{await requireCapability('RESIGNATION_REASON_ACCESS');assertId(id);try{
 const file=form.get('document');if(!(file instanceof File)||!file.size||file.size>10485760||!['application/pdf','image/png','image/jpeg'].includes(file.type))throw new ValidationError({document:'PDF, PNG, JPEG 파일을 10MB 이하로 첨부해 주세요.'});
 const bytes=Buffer.from(await file.arrayBuffer());const valid=file.type==='application/pdf'?bytes.subarray(0,5).toString()==='%PDF-':file.type==='image/png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(!valid)throw new ValidationError({document:'파일 형식과 내용을 확인해 주세요.'});
 const docId=await rpc('reserve_resignation_document',{p_id:id,p_filename:file.name.slice(0,200),p_mime:file.type,p_size:file.size});const client=await employeeClient();const {error}=await client.storage.from('resignation-letters').upload(`${id}/${docId}`,bytes,{contentType:file.type,upsert:false});if(error)throw error;await rpc('finish_resignation_document',{p_id:docId});
 }catch(error){return failure(error);}revalidatePath('/admin/offboarding/'+id);redirect(`/admin/offboarding/${id}?saved=1`);}
export async function saveAnnouncement(id:string|null,_state:FormState,form:FormData):Promise<FormState>{await requireCapability('ANNOUNCEMENT_MANAGE');if(id)assertId(id);const recordId=id||randomUUID();try{await rpc('save_announcement',{p_id:recordId,p_title:field(form,'title',200),p_body:field(form,'body',20000),p_publish:form.get('publish')==='on',p_version:versionFrom(form)});}catch(error){return failure(error);}revalidatePath('/announcements');redirect(`/announcements/${recordId}?saved=1`);}
export async function saveFamily(id:string|null,_state:FormState,form:FormData):Promise<FormState>{await requireCapability('EMPLOYEE_ACCESS');if(id)assertId(id);const recordId=id||randomUUID();try{await rpc('save_family_registration',{p_id:recordId,...familyInput(form),p_version:versionFrom(form)});}catch(error){return failure(error);}
 // Registration stays durable if mail credentials are absent. No private input is logged.
 if(!id)try{await runCompanyMail(recordId);}catch{/* Cron retries only unclaimed pending notifications. */}
 revalidatePath('/family-events');redirect(`/family-events/${recordId}/edit?saved=1`);
}
export async function publishFamily(id:string,_state:FormState,form:FormData):Promise<FormState>{await requireCapability('EMPLOYEE_ACCESS');assertId(id);const publish=form.get('publish')==='yes';try{await rpc('publish_family_post',{p_id:id,p_title:field(form,'board_title',200,publish),p_body:field(form,'board_body',5000,publish),p_publish:publish,p_version:versionFrom(form)});}catch(error){return failure(error);}revalidatePath('/family-events');redirect(`/family-events/${id}/edit?saved=1`);}
export async function saveBirthdayTemplate(_state:FormState,form:FormData):Promise<FormState>{await requireCapability('SETTINGS_MANAGE');let year:number;try{const input=templateInput(form);year=input.p_year;await rpc('save_birthday_template',{...input,p_version:versionFrom(form)});}catch(error){return failure(error);}revalidatePath('/admin/settings/birthday-email');redirect(`/admin/settings/birthday-email?year=${year}&saved=1`);}
